language: ruby
bundler_args: --without development
rvm:
  - 2.2.0
  - 2.3.1
  - jruby-9.0.5.0
  - rbx
  - ruby-head
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: ruby-head
branches:
  only:
    - master
sudo: false
